// Generated by gencpp from file messagenode/pos.msg
// DO NOT EDIT!


#ifndef MESSAGENODE_MESSAGE_POS_H
#define MESSAGENODE_MESSAGE_POS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messagenode
{
template <class ContainerAllocator>
struct pos_
{
  typedef pos_<ContainerAllocator> Type;

  pos_()
    : custom_msg()  {
    }
  pos_(const ContainerAllocator& _alloc)
    : custom_msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _custom_msg_type;
  _custom_msg_type custom_msg;





  typedef boost::shared_ptr< ::messagenode::pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messagenode::pos_<ContainerAllocator> const> ConstPtr;

}; // struct pos_

typedef ::messagenode::pos_<std::allocator<void> > pos;

typedef boost::shared_ptr< ::messagenode::pos > posPtr;
typedef boost::shared_ptr< ::messagenode::pos const> posConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messagenode::pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messagenode::pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace messagenode

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'messagenode': ['/home/haneesh/crazy_ws/src/messagenode/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::messagenode::pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messagenode::pos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messagenode::pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messagenode::pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messagenode::pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messagenode::pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messagenode::pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34bc0b7b6938cfa2480828862cdaf1a1";
  }

  static const char* value(const ::messagenode::pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34bc0b7b6938cfa2ULL;
  static const uint64_t static_value2 = 0x480828862cdaf1a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::messagenode::pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messagenode/pos";
  }

  static const char* value(const ::messagenode::pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messagenode::pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string custom_msg\n\
";
  }

  static const char* value(const ::messagenode::pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messagenode::pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.custom_msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messagenode::pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messagenode::pos_<ContainerAllocator>& v)
  {
    s << indent << "custom_msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.custom_msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGENODE_MESSAGE_POS_H
